project:
  type: website
  output-dir: _site

website:
  title: "Kara C. Hoover"
  site-url: https://kchoover14.github.io
  navbar:
    pinned: true
    background: primary
    left:
      - href: portfolio.qmd
        text: Portfolio
      - href: about.qmd
        text: About Me


    right:
      - icon: github
        href: https://github.com/kchoover14

format:
  html:
    theme: [cerulean, style-landing.scss]
    toc: false
